<a href="https://colab.research.google.com/github/hieulv416c/Url_content_detect/blob/main/ML_Compare.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# IMPORTANT: RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES,
# THEN FEEL FREE TO DELETE THIS CELL.
# NOTE: THIS NOTEBOOK ENVIRONMENT DIFFERS FROM KAGGLE'S PYTHON
# ENVIRONMENT SO THERE MAY BE MISSING LIBRARIES USED BY YOUR
# NOTEBOOK.
import kagglehub
lehieu12_df_topics_pkl_path = kagglehub.dataset_download('lehieu12/df-topics-pkl')

print('Data source import complete.')


In [ ]:
# Import the libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.style
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
import pickle
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score


In [ ]:
import pandas as pd

file_path = "/kaggle/input/df-topics-pkl/df_topics.pkl"
df = pd.read_pickle(file_path)
print(df.head())

   Topic_0  Topic_1  Topic_2  Topic_3  Topic_4  Topic_5  Topic_6  Topic_7  \
0      0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
1      0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
2      0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
3      0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
4      0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   

   Topic_8  Topic_9  ...  Topic_91  Topic_92  Topic_93  Topic_94  Topic_95  \
0      0.0      0.0  ...       0.0       0.0       0.0       0.0       0.0   
1      0.0      0.0  ...       0.0       0.0       0.0       0.0       0.0   
2      0.0      0.0  ...       0.0       0.0       0.0       0.0       0.0   
3      0.0      0.0  ...       0.0       0.0       0.0       0.0       0.0   
4      0.0      0.0  ...       0.0       0.0       0.0       0.0       0.0   

   Topic_96  Topic_97  Topic_98  Topic_99  label  
0       0.0      

In [ ]:
print(df['label'].value_counts())

label
0.0    44679
1.0    24180
Name: count, dtype: int64


In [ ]:
from sklearn.metrics import accuracy_score, classification_report
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from xgboost import XGBClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
import time  # Import thư viện đo thời gian

# Chỉ giữ lại các cột số
numeric_cols = df.select_dtypes(include=['number']).columns
df_numeric = df[numeric_cols]

# X là các đặc trưng (features) từ LDA
X = df_numeric.drop(columns=['label'], errors='ignore').values  # Bỏ cột nhãn nếu có
y = df['label']  # Nhãn phân loại (0 hoặc 1)

# Chia dữ liệu thành train/test (75-25) với stratify để giữ tỷ lệ nhãn
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# Chuẩn hóa dữ liệu (SVM nhạy cảm với scale)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Huấn luyện mô hình SVM với kernel tuyến tính
model = SVC(kernel='linear', C=1.0, random_state=42)  # Bạn có thể thử 'rbf' hoặc 'poly'

# Đo thời gian huấn luyện
start = time.time()
model.fit(X_train, y_train)
end = time.time()
print(f"Thời gian huấn luyện: {end - start:.2f} giây")

# Dự đoán trên tập test
y_pred = model.predict(X_test)

# Đánh giá mô hình
accuracy = accuracy_score(y_test, y_pred)
print(f"Độ chính xác của SVM: {accuracy:.4f}")

# Báo cáo chi tiết
print("Báo cáo phân loại:")
print(classification_report(y_test, y_pred))



Thời gian huấn luyện: 906.91 giây
Độ chính xác của SVM: 0.8893
Báo cáo phân loại:
              precision    recall  f1-score   support

         0.0       0.92      0.91      0.91     11170
         1.0       0.84      0.85      0.84      6045

    accuracy                           0.89     17215
   macro avg       0.88      0.88      0.88     17215
weighted avg       0.89      0.89      0.89     17215



#XGBoost

In [ ]:
from sklearn.metrics import accuracy_score, classification_report
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from xgboost import XGBClassifier
import time  # Import thư viện đo thời gian

# Chỉ giữ lại các cột số
numeric_cols = df.select_dtypes(include=['number']).columns
df_numeric = df[numeric_cols]

# X là các đặc trưng (features) từ LDA
X = df_numeric.drop(columns=['label'], errors='ignore').values  # Bỏ cột nhãn nếu có
y = df['label']  # Nhãn phân loại (0 hoặc 1)

# Chia dữ liệu thành train/test (75-25) với stratify để giữ tỷ lệ nhãn
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# Khởi tạo mô hình XGBoost
model = XGBClassifier(n_estimators=100, learning_rate=0.1, max_depth=6, random_state=42)

# Đo thời gian huấn luyện
start = time.time()
model.fit(X_train, y_train)
end = time.time()
print(f"Thời gian huấn luyện: {end - start:.2f} giây")

# Dự đoán trên tập test
y_pred = model.predict(X_test)

# Đánh giá mô hình
accuracy = accuracy_score(y_test, y_pred)
print(f"Độ chính xác của mô hình XGBoost: {accuracy:.4f}")
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import numpy as np
# Tính các chỉ số đánh giá
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)  # Căn bậc hai của MSE
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
# Hiển thị kết quả
print(f"MSE: {mse:.4f}")
print(f"RMSE: {rmse:.4f}")
print(f"MAE: {mae:.4f}")
print(f"R² Score: {r2:.4f}")
# Báo cáo chi tiết
print("Báo cáo phân loại:")
print(classification_report(y_test, y_pred))


Thời gian huấn luyện: 1.74 giây
Độ chính xác của mô hình XGBoost: 0.9272
MSE: 0.0728
RMSE: 0.2698
MAE: 0.0728
R² Score: 0.6805
Báo cáo phân loại:
              precision    recall  f1-score   support

         0.0       0.95      0.93      0.94     11170
         1.0       0.88      0.91      0.90      6045

    accuracy                           0.93     17215
   macro avg       0.92      0.92      0.92     17215
weighted avg       0.93      0.93      0.93     17215



In [ ]:
import time
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score, classification_report
from sklearn.preprocessing import StandardScaler

# # Chỉ giữ lại các cột số
# numeric_cols = df.select_dtypes(include=['number']).columns
# df_numeric = df[numeric_cols]

# # X là các đặc trưng (features) từ LDA
# X = df_numeric.drop(columns=['label'], errors='ignore').values  # Bỏ cột nhãn nếu có
# y = df['label']  # Nhãn phân loại (0 hoặc 1)

# # Chia dữ liệu thành train/test (80-20)
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)
# Đo thời gian huấn luyện
# Chỉ giữ lại các cột số

# Chuẩn hóa dữ liệu (MLP nhạy cảm với scale)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Khởi tạo mô hình MLP
model = MLPClassifier(
    hidden_layer_sizes=(100, 50),
    activation='relu',
    solver='adam',
    max_iter=500,
    random_state=42
)

# Đo thời gian huấn luyện
start = time.time()
model.fit(X_train, y_train)
end = time.time()
print(f"Thời gian huấn luyện: {end - start:.2f} giây")
# Đo thời gian dự đoán
start_pred = time.time()
y_pred = model.predict(X_test)
end_pred = time.time()
print(f"Thời gian dự đoán: {end_pred - start_pred:.2f} giây")
# Dự đoán trên tập test
y_pred = model.predict(X_test)

# Đánh giá mô hình
accuracy = accuracy_score(y_test, y_pred)
print(f"Độ chính xác của MLP Classifier: {accuracy:.4f}")

# Báo cáo chi tiết
print("Báo cáo phân loại:")
print(classification_report(y_test, y_pred))

Thời gian huấn luyện: 86.39 giây
Thời gian dự đoán: 0.04 giây
Độ chính xác của MLP Classifier: 0.9464
Báo cáo phân loại:
              precision    recall  f1-score   support

         0.0       0.96      0.95      0.96     11170
         1.0       0.91      0.93      0.92      6045

    accuracy                           0.95     17215
   macro avg       0.94      0.94      0.94     17215
weighted avg       0.95      0.95      0.95     17215



In [ ]:
import time
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Khởi tạo mô hình
model = LogisticRegression(max_iter=1000, random_state=42)

# Đo thời gian huấn luyện
start = time.time()
model.fit(X_train, y_train)
end = time.time()

print(f"Thời gian huấn luyện: {end - start:.2f} giây")
# Đo thời gian dự đoán
start_pred = time.time()
y_pred = model.predict(X_test)
end_pred = time.time()
print(f"Thời gian dự đoán KNN: {end_pred - start_pred:.2f} giây")
# Dự đoán trên tập test
y_pred = model.predict(X_test)

# Đánh giá mô hình
accuracy = accuracy_score(y_test, y_pred)
print(f"Độ chính xác của Logistic Regression: {accuracy:.4f}")

# Ma trận nhầm lẫn
cm = confusion_matrix(y_test, y_pred)
print("Ma trận nhầm lẫn:")
print(cm)

# Báo cáo phân loại (Precision, Recall, F1-score)
print("Báo cáo phân loại:")
print(classification_report(y_test, y_pred))


Thời gian huấn luyện: 0.34 giây
Thời gian dự đoán KNN: 0.00 giây
Độ chính xác của Logistic Regression: 0.8887
Ma trận nhầm lẫn:
[[10166  1004]
 [  912  5133]]
Báo cáo phân loại:
              precision    recall  f1-score   support

         0.0       0.92      0.91      0.91     11170
         1.0       0.84      0.85      0.84      6045

    accuracy                           0.89     17215
   macro avg       0.88      0.88      0.88     17215
weighted avg       0.89      0.89      0.89     17215



K-Nearest Neighbors : Classifier

In [ ]:
import time
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Chuẩn hóa dữ liệu (KNN nhạy cảm với scale)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Huấn luyện mô hình KNN với k=5
k = 5  # Có thể thay đổi giá trị này
model = KNeighborsClassifier(n_neighbors=k)

# Đo thời gian huấn luyện
start_train = time.time()
model.fit(X_train, y_train)
end_train = time.time()
print(f"Thời gian huấn luyện KNN: {end_train - start_train:.2f} giây")

# Đo thời gian dự đoán
start_pred = time.time()
y_pred = model.predict(X_test)
end_pred = time.time()
print(f"Thời gian dự đoán KNN: {end_pred - start_pred:.2f} giây")

# Đánh giá mô hình
accuracy = accuracy_score(y_test, y_pred)
print(f"Độ chính xác của KNN (k={k}): {accuracy:.4f}")

# Ma trận nhầm lẫn
cm = confusion_matrix(y_test, y_pred)
print("Ma trận nhầm lẫn:")
print(cm)

# Báo cáo phân loại (Precision, Recall, F1-score)
print("Báo cáo phân loại:")
print(classification_report(y_test, y_pred))


Thời gian huấn luyện KNN: 0.01 giây
Thời gian dự đoán KNN: 5.27 giây
Độ chính xác của KNN (k=5): 0.9197
Ma trận nhầm lẫn:
[[10565   605]
 [  777  5268]]
Báo cáo phân loại:
              precision    recall  f1-score   support

         0.0       0.93      0.95      0.94     11170
         1.0       0.90      0.87      0.88      6045

    accuracy                           0.92     17215
   macro avg       0.91      0.91      0.91     17215
weighted avg       0.92      0.92      0.92     17215



Support Vector Machine : Classifier

In [ ]:
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
# Chuẩn hóa dữ liệu (SVM nhạy cảm với scale)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Huấn luyện mô hình SVM với kernel tuyến tính
model = SVC(kernel='linear', C=1.0, random_state=42)  # Bạn có thể thử 'rbf' hoặc 'poly'
model.fit(X_train, y_train)

# Dự đoán trên tập test
y_pred = model.predict(X_test)

# Đánh giá mô hình
accuracy = accuracy_score(y_test, y_pred)
print(f"Độ chính xác của SVM: {accuracy:.4f}")
# # Tính các chỉ số đánh giá
# mse = mean_squared_error(y_test, y_pred)
# rmse = np.sqrt(mse)  # Căn bậc hai của MSE
# mae = mean_absolute_error(y_test, y_pred)
# r2 = r2_score(y_test, y_pred)

# # Hiển thị kết quả
# print(f"MSE: {mse:.4f}")
# print(f"RMSE: {rmse:.4f}")
# print(f"MAE: {mae:.4f}")
# print(f"R² Score: {r2:.4f}")
# Báo cáo chi tiết
print("Báo cáo phân loại:")
print(classification_report(y_test, y_pred))


Naive Bayes : Classifier

In [ ]:
import time
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Khởi tạo mô hình Naive Bayes
model = GaussianNB()

# Đo thời gian huấn luyện
start_train = time.time()
model.fit(X_train, y_train)
end_train = time.time()
print(f"Thời gian huấn luyện Naive Bayes: {end_train - start_train:.4f} giây")

# Đo thời gian dự đoán
start_pred = time.time()
y_pred = model.predict(X_test)
end_pred = time.time()
print(f"Thời gian dự đoán Naive Bayes: {end_pred - start_pred:.4f} giây")

# Đánh giá mô hình
accuracy = accuracy_score(y_test, y_pred)
print(f"Độ chính xác của Naive Bayes: {accuracy:.4f}")

# Ma trận nhầm lẫn
cm = confusion_matrix(y_test, y_pred)
print("Ma trận nhầm lẫn:")
print(cm)

# Báo cáo phân loại
print("Báo cáo phân loại:")
print(classification_report(y_test, y_pred))


Thời gian huấn luyện Naive Bayes: 0.1317 giây
Thời gian dự đoán Naive Bayes: 0.0335 giây
Độ chính xác của Naive Bayes: 0.8173
Ma trận nhầm lẫn:
[[10391   779]
 [ 2366  3679]]
Báo cáo phân loại:
              precision    recall  f1-score   support

         0.0       0.81      0.93      0.87     11170
         1.0       0.83      0.61      0.70      6045

    accuracy                           0.82     17215
   macro avg       0.82      0.77      0.78     17215
weighted avg       0.82      0.82      0.81     17215



Decision Trees

In [ ]:
import time
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Khởi tạo mô hình Decision Tree
model = DecisionTreeClassifier(criterion='gini', max_depth=None, random_state=42)

# Đo thời gian huấn luyện
start_train = time.time()
model.fit(X_train, y_train)
end_train = time.time()
print(f"Thời gian huấn luyện Decision Tree: {end_train - start_train:.4f} giây")

# Đo thời gian dự đoán
start_pred = time.time()
y_pred = model.predict(X_test)
end_pred = time.time()
print(f"Thời gian dự đoán Decision Tree: {end_pred - start_pred:.4f} giây")

# Đánh giá mô hình
accuracy = accuracy_score(y_test, y_pred)
print(f"Độ chính xác của Decision Tree: {accuracy:.4f}")

# Ma trận nhầm lẫn
cm = confusion_matrix(y_test, y_pred)
print("Ma trận nhầm lẫn:")
print(cm)

# Báo cáo phân loại
print("Báo cáo phân loại:")
print(classification_report(y_test, y_pred))


Thời gian huấn luyện Decision Tree: 4.2644 giây
Thời gian dự đoán Decision Tree: 0.0083 giây
Độ chính xác của Decision Tree: 0.9377
Ma trận nhầm lẫn:
[[10501   669]
 [  404  5641]]
Báo cáo phân loại:
              precision    recall  f1-score   support

         0.0       0.96      0.94      0.95     11170
         1.0       0.89      0.93      0.91      6045

    accuracy                           0.94     17215
   macro avg       0.93      0.94      0.93     17215
weighted avg       0.94      0.94      0.94     17215



 Random Forest

In [ ]:
import time
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Khởi tạo mô hình Random Forest
model = RandomForestClassifier(n_estimators=100, max_depth=None, random_state=42)

# Đo thời gian huấn luyện
start_train = time.time()
model.fit(X_train, y_train)
end_train = time.time()
print(f"Thời gian huấn luyện Random Forest: {end_train - start_train:.4f} giây")

# Đo thời gian dự đoán
start_pred = time.time()
y_pred = model.predict(X_test)
end_pred = time.time()
print(f"Thời gian dự đoán Random Forest: {end_pred - start_pred:.4f} giây")

# Đánh giá mô hình
accuracy = accuracy_score(y_test, y_pred)
print(f"Độ chính xác của Random Forest: {accuracy:.4f}")

# Ma trận nhầm lẫn
cm = confusion_matrix(y_test, y_pred)
print("Ma trận nhầm lẫn:")
print(cm)

# Báo cáo phân loại
print("Báo cáo phân loại:")
print(classification_report(y_test, y_pred))


Thời gian huấn luyện Random Forest: 15.7457 giây
Thời gian dự đoán Random Forest: 0.4140 giây
Độ chính xác của Random Forest: 0.9562
Ma trận nhầm lẫn:
[[10806   364]
 [  390  5655]]
Báo cáo phân loại:
              precision    recall  f1-score   support

         0.0       0.97      0.97      0.97     11170
         1.0       0.94      0.94      0.94      6045

    accuracy                           0.96     17215
   macro avg       0.95      0.95      0.95     17215
weighted avg       0.96      0.96      0.96     17215



Gradient Boosting Classifier

In [ ]:
import time
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Khởi tạo mô hình Gradient Boosting
model = GradientBoostingClassifier(n_estimators=100, learning_rate=0.1, max_depth=3, random_state=42)

# Đo thời gian huấn luyện
start_train = time.time()
model.fit(X_train, y_train)
end_train = time.time()
print(f"Thời gian huấn luyện Gradient Boosting: {end_train - start_train:.4f} giây")

# Đo thời gian dự đoán
start_pred = time.time()
y_pred = model.predict(X_test)
end_pred = time.time()
print(f"Thời gian dự đoán Gradient Boosting: {end_pred - start_pred:.4f} giây")

# Đánh giá mô hình
accuracy = accuracy_score(y_test, y_pred)
print(f"Độ chính xác của Gradient Boosting: {accuracy:.4f}")

# Ma trận nhầm lẫn
cm = confusion_matrix(y_test, y_pred)
print("Ma trận nhầm lẫn:")
print(cm)

# Báo cáo phân loại
print("Báo cáo phân loại:")
print(classification_report(y_test, y_pred))


Thời gian huấn luyện Gradient Boosting: 37.0111 giây
Thời gian dự đoán Gradient Boosting: 0.0315 giây
Độ chính xác của Gradient Boosting: 0.9131
Ma trận nhầm lẫn:
[[10303   867]
 [  629  5416]]
Báo cáo phân loại:
              precision    recall  f1-score   support

         0.0       0.94      0.92      0.93     11170
         1.0       0.86      0.90      0.88      6045

    accuracy                           0.91     17215
   macro avg       0.90      0.91      0.91     17215
weighted avg       0.91      0.91      0.91     17215



CatBoost Classifier

In [ ]:
import time
from catboost import CatBoostClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Khởi tạo mô hình CatBoost
model = CatBoostClassifier(iterations=100, learning_rate=0.1, depth=6, verbose=0, random_state=42)

# Đo thời gian huấn luyện
start_train = time.time()
model.fit(X_train, y_train)
end_train = time.time()
print(f"Thời gian huấn luyện CatBoost: {end_train - start_train:.4f} giây")

# Đo thời gian dự đoán
start_pred = time.time()
y_pred = model.predict(X_test)
end_pred = time.time()
print(f"Thời gian dự đoán CatBoost: {end_pred - start_pred:.4f} giây")

# Đánh giá mô hình
accuracy = accuracy_score(y_test, y_pred)
print(f"Độ chính xác của CatBoost: {accuracy:.4f}")

# Ma trận nhầm lẫn
cm = confusion_matrix(y_test, y_pred)
print("Ma trận nhầm lẫn:")
print(cm)

# Báo cáo phân loại
print("Báo cáo phân loại:")
print(classification_report(y_test, y_pred))


Thời gian huấn luyện CatBoost: 4.9926 giây
Thời gian dự đoán CatBoost: 0.5210 giây
Độ chính xác của CatBoost: 0.9211
Ma trận nhầm lẫn:
[[10406   764]
 [  595  5450]]
Báo cáo phân loại:
              precision    recall  f1-score   support

         0.0       0.95      0.93      0.94     11170
         1.0       0.88      0.90      0.89      6045

    accuracy                           0.92     17215
   macro avg       0.91      0.92      0.91     17215
weighted avg       0.92      0.92      0.92     17215



Multi-layer Perceptron classifier